copy output_files\mcr2.rbf "Domino Man.rbf"
copy output_files\mcr2.rbf "Kozmik Kroozr.rbf"
copy output_files\mcr2.rbf "Satans Hollow.rbf"
copy output_files\mcr2.rbf "Tron.rbf"
copy output_files\mcr2.rbf "Two Tigers.rbf"
copy output_files\mcr2.rbf "Wacko.rbf"
