set_global_assignment -name VERILOG_MACRO "CORENAME=\"JTDD\""
set_global_assignment -name VERILOG_MACRO "GAMETOP=jtdd_game"
set_global_assignment -name VERILOG_MACRO "COLORW=4"
set_global_assignment -name VERILOG_MACRO "BUTTONS=3"
set_global_assignment -name VERILOG_MACRO "JTFRAME_CLK24=1"
