programs = pcb2ver bin2m bin2raw drop1 raw2wav cen_gen bin2hex byte2hex msg2hex lut2hex hex2bin mamefilter mame2dip

all: $(programs)
	cp $(programs) ../bin	

pcb2ver:

bin2m:

bin2raw:

drop1:

WaveWritter.o:

raw2wav: WaveWritter.o

cen_gen:

bin2hex:

byte2hex:

msg2hex:

lut2hex:

hex2bin:

mamefilter:

mamegame.o:

mame2dip: mame2dip.cc mamegame.o
	g++ mame2dip.cc mamegame.o -o mame2dip -lxerces-c