all: pcb2ver bin2m bin2raw drop1 raw2wav cen_gen bin2hex byte2hex msg2hex lut2hex
	cp pcb2ver bin2m bin2raw drop1 raw2wav cen_gen bin2hex msg2hex lut2hex ../bin

pcb2ver:

bin2m:

bin2raw:

drop1:

WaveWritter.o:

raw2wav: WaveWritter.o

cen_gen:

bin2hex:

byte2hex:

msg2hex:

lut2hex:
