mmr: mmr.cc config.h  dip_base.h  dips.h  inputs.h  mappers.h  romentry.h  romsets.h ../modules/jtframe/cc/mamegame.cc
	g++ -I ../modules/jtframe/cc ../modules/jtframe/cc/mamegame.cc mmr.cc -o mmr -lxerces-c
