set_global_assignment -name VERILOG_MACRO "CORENAME=\"JTDD2\""
set_global_assignment -name VERILOG_MACRO "GAMETOP=jtdd2_game"
set_global_assignment -name VERILOG_MACRO "COLORW=4"
set_global_assignment -name VERILOG_MACRO "DD2=1"
set_global_assignment -name VERILOG_MACRO "BUTTONS=3"
set_global_assignment -name VERILOG_MACRO "JTFRAME_SDRAM_REPACK=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_CLK24=1"
set_global_assignment -name VERILOG_MACRO "TV80S=1"
